feat: Unique Kafka Consumer GroupID
argoproj-labs/argo-dataflow pull request #251
Opened 2021-08-14 19:03 UTC by sarabala1979

Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

2021-08-14 19:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj-labs/argo-dataflow?pullRequest=251) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj-labs/argo-dataflow?pullRequest=251) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj-labs/argo-dataflow?pullRequest=251) it.</sub>

2021-08-16 14:04 UTC, alexec commented
This is the right direction. We should use this generator for creating the STAN `DurableName` too.

2021-08-16 16:13 UTC, sarabala1979 commented
@alexec can you replace the below place also?
https://github.com/argoproj-labs/argo-dataflow/blob/3be7f7f8ed7d4d1f88f2e440fc66768311db44a0/runner/sidecar/source/db/db.go#L53

2021-08-18 18:01 UTC, alexec requested changes

2021-08-19 14:11 UTC, alexec approved these changes

2021-08-19 14:11 UTC, merged